import { Sequelize, Model, ModelStatic } from 'sequelize';export const sequelize: Sequelize;
export const SequelizeInstance: typeof Sequelize;// Add individual model exports
export const Brand: ModelStatic<Model>;
export const Contest: ModelStatic<Model>;
export const Genre: ModelStatic<Model>;
export const Inscription: ModelStatic<Model>;
export const Log: ModelStatic<Model>;
export const Manager: ModelStatic<Model>;
export const Media: ModelStatic<Model>;
export const Param: ModelStatic<Model>;
export const Role: ModelStatic<Model>;
export const SocialMedia: ModelStatic<Model>;
export const Sponsor: ModelStatic<Model>;
export const State: ModelStatic<Model>;
export const TagType: ModelStatic<Model>;
export const Tag: ModelStatic<Model>;
export const TMRVote: ModelStatic<Model>;
export const Vote: ModelStatic<Model>;
export const Voter: ModelStatic<Model>;
export const ContestGenre: ModelStatic<Model>;
export const ContestManager: ModelStatic<Model>;
export const ContestMedia: ModelStatic<Model>;
export const ContestParam: ModelStatic<Model>;
export const ContestSocial: ModelStatic<Model>;
export const ContestSponsor: ModelStatic<Model>;
export const InscriptionTag: ModelStatic<Model>;
